---
title: "forecast_illustration"
author: "Jorge Arroyo-Esquivel"
date: "2023-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load libraries and data
```{r,warning=FALSE}
rm(list=ls())
library(ggplot2)
library(dplyr)
library(ggpubr)
library(broom)
library(lme4)
library(scales)
load("test_predictions_and_residuals.RData")
load("null_test_predictions_and_residuals.RData")
load("EDM_test_predictions_and_residuals.RData")
load("lstm_test_predictions_and_residuals.RData")
```

#Choose a time series and process it
```{r}
allPredictions <- testPredictions %>% full_join(ARIMAPredictions %>% mutate(ModelType = "Time Agnostic",ArchitectureType = "ARIMA",RepNumber = 1)) %>% full_join(LSTMPredictions %>% mutate(ModelType = "Time Agnostic",ArchitectureType = "LSTM",RepNumber = 1)) %>% full_join(EDMPredictions %>% mutate(ModelType = "Time Agnostic",ArchitectureType = "EDM",RepNumber = 1))

selectedCommunitySize = 10
selectedObservationError = 0
selectedTimeSeriesID = 1

selectedTimeSeries <- allPredictions %>% filter(CommunitySize == selectedCommunitySize, ObservationError == selectedObservationError,TimeSeriesID == selectedTimeSeriesID) %>% group_by(ModelType,ArchitectureType,TrainingSize,Time,PopID) %>% summarise(RealValue = RealValue,MeanPrediction = mean(LogDensity),SEPrediction = sd(LogDensity)/sqrt(n())) %>% mutate(Lower95 = MeanPrediction - 1.96*SEPrediction, Higher95 = MeanPrediction + 1.96*SEPrediction) %>% select(-SEPrediction) %>% arrange(TrainingSize,PopID,Time)

selectedARIMA <- ARIMAPredictionsSD %>% mutate(ModelType = "ARIMA",ArchitectureType = "ARIMA") %>%  group_by(ModelType,ArchitectureType,TrainingSize,Time,PopID) %>% filter(CommunitySize == selectedCommunitySize, ObservationError == selectedObservationError,TimeSeriesID == selectedTimeSeriesID) %>% select(-CommunitySize,-ObservationError,-TimeSeriesID) %>% arrange(TrainingSize,PopID,Time)

selectedLSTM <- LSTMPredictionsSD %>% mutate(ModelType = "LSTM",ArchitectureType = "LSTM") %>%  group_by(ModelType,ArchitectureType,TrainingSize,Time,PopID) %>% filter(CommunitySize == selectedCommunitySize, ObservationError == selectedObservationError,TimeSeriesID == selectedTimeSeriesID) %>% select(-CommunitySize,-ObservationError,-TimeSeriesID) %>% arrange(TrainingSize,PopID,Time)

selectedEDM <- EDMPredictionsSD %>% mutate(ModelType = "EDM",ArchitectureType = "EDM") %>%  group_by(ModelType,ArchitectureType,TrainingSize,Time,PopID) %>% filter(CommunitySize == selectedCommunitySize, ObservationError == selectedObservationError,TimeSeriesID == selectedTimeSeriesID) %>% select(-CommunitySize,-ObservationError,-TimeSeriesID) %>% arrange(TrainingSize,PopID,Time)

selectedTimeSeries[selectedTimeSeries$ArchitectureType == "ARIMA",8] = selectedARIMA$Lower95
selectedTimeSeries[selectedTimeSeries$ArchitectureType == "ARIMA",9] = selectedARIMA$Higher95

selectedTimeSeries[selectedTimeSeries$ArchitectureType == "LSTM",8] = selectedLSTM$Lower95
selectedTimeSeries[selectedTimeSeries$ArchitectureType == "LSTM",9] = selectedLSTM$Higher95

selectedTimeSeries[selectedTimeSeries$ArchitectureType == "EDM",8] = selectedEDM$Lower95
selectedTimeSeries[selectedTimeSeries$ArchitectureType == "EDM",9] = selectedEDM$Higher95

selectedTimeSeries <- selectedTimeSeries %>% filter(Time<=TrainingSize+20,Time!=TrainingSize)
```

#Make time series plot for each different model with 30 training size
```{r}
chosenTrainingSize = 30
realTimeSeries <- read.csv(paste(sep="",paste(sep="_","../Data/timeSeries_communitySize",selectedCommunitySize,"observationError","0.0","rep",selectedTimeSeriesID),".csv"),sep='\t',header=FALSE)[,(chosenTrainingSize-20):(chosenTrainingSize+20)]

realTimeSeries <- data.frame(Time = rep((chosenTrainingSize-20):(chosenTrainingSize+20),selectedCommunitySize),PopID = rep(1:selectedCommunitySize,each = 41),RealValue = as.vector(t(realTimeSeries)))

samplePopulations <- c(2,3,6,9)
realTimeSeries <- realTimeSeries %>% filter(PopID %in%(samplePopulations)) %>% mutate(RealValue = RealValue)
realTimeSeries$PopID <- as.factor(realTimeSeries$PopID)
selectedTimeSeries <- selectedTimeSeries %>% filter(PopID %in%(samplePopulations)) %>%  mutate(Higher95 = Higher95, Lower95 = Lower95,MeanPrediction = MeanPrediction)
selectedTimeSeries$PopID <- as.factor(selectedTimeSeries$PopID)
```

```{r}
p1 <- ggplot(realTimeSeries,aes(Time,RealValue),fill=(PopID))+geom_point(aes(colour=(PopID)))+ geom_line(data=selectedTimeSeries %>% filter(ModelType == "ARIMA",TrainingSize == chosenTrainingSize),aes(Time,MeanPrediction,color=(PopID))) + geom_ribbon(data = selectedTimeSeries %>% filter(ModelType == "ARIMA",TrainingSize == chosenTrainingSize)%>% mutate(Lower95 = max(-10,Lower95),Higher95 = min(10,Higher95)),aes(ymin = Lower95, ymax = Higher95,fill = (PopID)),alpha = 0.2) + ggtitle("ARIMA") + ylab("Population Log Density") +theme_bw()+ theme(text = element_text(size=14))+ ylim(-10,10)

p2 <- ggplot(realTimeSeries,aes(Time,RealValue,fill=(PopID)))+geom_point(aes(colour=(PopID)))+ geom_line(data=selectedTimeSeries %>% filter(ModelType == "LSTM",ArchitectureType == "LSTM",TrainingSize == chosenTrainingSize),aes(Time,MeanPrediction,color=(PopID))) + geom_ribbon(data = selectedTimeSeries %>% filter(ModelType == "LSTM",ArchitectureType == "LSTM",TrainingSize == chosenTrainingSize)%>% mutate(Lower95 = max(-10,Lower95),Higher95 = min(10,Higher95)),aes(ymin = Lower95, ymax = Higher95,group = (PopID)),alpha = 0.2) + ggtitle("LSTM") + ylab("Population Log Density")+ theme_bw()+theme(text = element_text(size=14))+ ylim(-10,10)

p3 <- ggplot(realTimeSeries,aes(Time,RealValue,fill=(PopID)))+geom_point(aes(colour=(PopID)))+ geom_line(data=selectedTimeSeries %>% filter(ModelType == "EDM",ArchitectureType == "EDM",TrainingSize == chosenTrainingSize),aes(Time,MeanPrediction,color=(PopID))) + geom_ribbon(data = selectedTimeSeries %>% filter(ModelType == "EDM",ArchitectureType == "EDM",TrainingSize == chosenTrainingSize)%>% mutate(Lower95 = max(-10,Lower95),Higher95 = min(10,Higher95)),aes(ymin = Lower95, ymax = Higher95,group = (PopID)),alpha = 0.2) + ggtitle("EDM") + ylab("Population Log Density")+ theme_bw()+theme(text = element_text(size=14))+ ylim(-10,10)

p4 <- ggplot(realTimeSeries,aes(Time,RealValue,fill=(PopID)))+geom_point(aes(colour=(PopID)))+ geom_line(data=selectedTimeSeries %>% filter(ModelType == "Time Aware",ArchitectureType == "NODE",TrainingSize == chosenTrainingSize),aes(Time,MeanPrediction,color=(PopID))) + geom_ribbon(data = selectedTimeSeries %>% filter(ModelType == "Time Aware",ArchitectureType == "NODE",TrainingSize == chosenTrainingSize)%>% mutate(Lower95 = max(-10,Lower95),Higher95 = min(10,Higher95)),aes(ymin = Lower95, ymax = Higher95,group = (PopID)),alpha = 0.2) + ggtitle("Time Aware NODE") + ylab("Population Log Density")+ theme_bw()+theme(text = element_text(size=14))+ ylim(-10,10)

p5 <- ggplot(realTimeSeries,aes(Time,RealValue,fill=(PopID)))+geom_point(aes(colour=(PopID)))+ geom_line(data=selectedTimeSeries %>% filter(ModelType == "Time Agnostic",ArchitectureType == "NODE",TrainingSize == chosenTrainingSize),aes(Time,MeanPrediction,color=(PopID))) + geom_ribbon(data = selectedTimeSeries %>% filter(ModelType == "Time Agnostic",ArchitectureType == "NODE",TrainingSize == chosenTrainingSize)%>% mutate(Lower95 = max(-10,Lower95),Higher95 = min(10,Higher95)),aes(ymin = Lower95, ymax = Higher95,group = (PopID)),alpha = 0.2) + ggtitle("Time Agnostic NODE") + ylab("Population Log Density")+ theme_bw()+theme(text = element_text(size=14))+ ylim(-10,10)

p6 <- ggplot(realTimeSeries,aes(Time,RealValue,fill=(PopID)))+geom_point(aes(colour=(PopID)))+ geom_line(data=selectedTimeSeries %>% filter(ModelType == "Time Aware",ArchitectureType == "UDE",TrainingSize == chosenTrainingSize),aes(Time,MeanPrediction,color=(PopID))) + geom_ribbon(data = selectedTimeSeries %>% filter(ModelType == "Time Aware",ArchitectureType == "UDE",TrainingSize == chosenTrainingSize)%>% mutate(Lower95 = max(-10,Lower95),Higher95 = min(10,Higher95)),aes(ymin = Lower95, ymax = Higher95,group = (PopID)),alpha = 0.2) + ggtitle("Time Aware UDE") + ylab("Population Log Density")+theme_bw()+ theme(text = element_text(size=14))+ ylim(-10,10)

p7 <- ggplot(realTimeSeries,aes(Time,RealValue,fill=(PopID)))+geom_point(aes(colour=(PopID)))+ geom_line(data=selectedTimeSeries %>% filter(ModelType == "Time Agnostic",ArchitectureType == "UDE",TrainingSize == chosenTrainingSize),aes(Time,MeanPrediction,color=(PopID))) + geom_ribbon(data = selectedTimeSeries %>% filter(ModelType == "Time Agnostic",ArchitectureType == "UDE",TrainingSize == chosenTrainingSize) %>% mutate(Lower95 = max(-10,Lower95),Higher95 = min(10,Higher95)),aes(ymin = Lower95, ymax = Higher95,group = (PopID)),alpha = 0.2) + ggtitle("Time Agnostic UDE") + theme_bw() + ylab("Population Log Density")+ theme(text = element_text(size=14)) + ylim(-10,10)

ggarrange(p1,p2,p3,p4,p5,p6,p7,common.legend = TRUE,legend='none')
```   

#Uncertainty spread seems to be terrible on ARIMA
#Let's analyze that statistically
```{r}
timeSeriesSpread <- allPredictions %>% filter(Time<=TrainingSize+20) %>% group_by(CommunitySize,ObservationError,ModelType,ArchitectureType,TrainingSize,Time,TimeSeriesID,PopID) %>% summarise(RealValue = RealValue,MeanPrediction = mean(LogDensity),SEPrediction = sd(LogDensity)/sqrt(n())) %>% mutate(Lower95 = MeanPrediction - 1.96*SEPrediction, Higher95 = MeanPrediction + 1.96*SEPrediction) %>% select(-SEPrediction) %>% arrange(TrainingSize,PopID,Time)

selectedARIMA <- ARIMAPredictionsSD %>% mutate(ModelType = "Time Agnostic",ArchitectureType = "ARIMA") %>% filter(Time<=TrainingSize+20) %>%  group_by(CommunitySize,ObservationError,ModelType,ArchitectureType,TrainingSize,Time,PopID,TimeSeriesID) %>% select(-CommunitySize,-ObservationError) %>% arrange(TrainingSize,PopID,Time)

selectedLSTM <- LSTMPredictionsSD %>% mutate(ModelType = "Time Agnostic",ArchitectureType = "LSTM") %>% filter(Time<=TrainingSize+20) %>%  group_by(CommunitySize,ObservationError,ModelType,ArchitectureType,TrainingSize,Time,PopID,TimeSeriesID) %>% select(-CommunitySize,-ObservationError) %>% arrange(TrainingSize,PopID,Time)

selectedEDM <- EDMPredictionsSD %>% mutate(ModelType = "Time Agnostic",ArchitectureType = "EDM") %>% filter(Time<=TrainingSize+20) %>%  group_by(CommunitySize,ObservationError,ModelType,ArchitectureType,TrainingSize,Time,PopID,TimeSeriesID) %>% select(-CommunitySize,-ObservationError,-TimeSeriesID) %>% arrange(TrainingSize,PopID,Time)

timeSeriesSpread[timeSeriesSpread$ArchitectureType == "ARIMA",10] = selectedARIMA$Lower95
timeSeriesSpread[timeSeriesSpread$ArchitectureType == "ARIMA",11] = selectedARIMA$Higher95

timeSeriesSpread[timeSeriesSpread$ArchitectureType == "LSTM",10] = selectedLSTM$Lower95
timeSeriesSpread[timeSeriesSpread$ArchitectureType == "LSTM",11] = selectedLSTM$Higher95

timeSeriesSpread[timeSeriesSpread$ArchitectureType == "EDM",10] = selectedEDM$Lower95
timeSeriesSpread[timeSeriesSpread$ArchitectureType == "EDM",11] = selectedEDM$Higher95

timeSeriesSpread <- timeSeriesSpread %>% mutate(Spread = Higher95-Lower95) %>% mutate(CV = abs(Spread/MeanPrediction))

timeSeriesSpread %>% lmer(Spread~ModelType+ArchitectureType+TrainingSize+CommunitySize+ObservationError+(1|TimeSeriesID), data = .) %>% 
  anova() %>% tidy() %>% mutate(contribution = sumsq/sum(sumsq)) %>% filter(term != "Residuals") %>% ggplot(aes(reorder(term,contribution),contribution* 100,fill=term)) +
  geom_bar(stat='identity') + xlab("Variable") + ylab("Contribution to variation (%)") + theme_bw() + ylim(0,50) + labs(fill = "Term") + theme(text=element_text(size=20))
```
```{r}
timeSeriesSpread %>% ggplot(aes(ModelType,Spread,fill = ModelType))+geom_violin() + theme_bw() + xlab("Model Type") + ylab("Size of Confidence Intervals") +    scale_y_continuous(trans='log10',
                     breaks=trans_breaks('log10', function(x) 10^x),
                     labels=trans_format('log10', math_format(10^.x))) + theme(legend.position="none",text=element_text(size=24))+stat_summary(
    geom = "point",
    fun = "mean",
    col = "black",
    size = 5,
    shape = 24,
    fill = "red"
  )

timeSeriesSpread %>% ggplot(aes(ArchitectureType,Spread,fill = ArchitectureType))+geom_violin() + theme_bw() + xlab("Architecture Type") + ylab("Size of Confidence Intervals") +    scale_y_continuous(trans='log10',
                     breaks=trans_breaks('log10', function(x) 10^x),
                     labels=trans_format('log10', math_format(10^.x))) + theme(legend.position="none",text=element_text(size=24))+stat_summary(
    geom = "point",
    fun = "mean",
    col = "black",
    size = 5,
    shape = 24,
    fill = "red"
  )
```
```{r}
#Time series of size of confidence intervals
timeSeriesSpread %>% mutate(ForecastHorizon = Time-TrainingSize) %>% filter(ForecastHorizon>0) %>%  ggplot(aes(ForecastHorizon,Spread,color=ArchitectureType)) + geom_point(position=position_dodge(width=0.9),size=2)+scale_y_continuous(trans='log10',
                     breaks=trans_breaks('log10', function(x) 10^x),
                     labels=trans_format('log10', math_format(10^.x)))+labs(x="Forecasting Horizon",y="Size of Confidence Interval",color="Architecture Type") + theme_bw() + theme(text = element_text(size=22))
timeSeriesSpread %>% mutate(ForecastHorizon = Time-TrainingSize) %>% filter(ForecastHorizon>0) %>%  ggplot(aes(ForecastHorizon,Spread,color=ModelType)) + geom_point(position=position_dodge(width=0.9),size=2)+scale_y_continuous(trans='log10',
                     breaks=trans_breaks('log10', function(x) 10^x),
                     labels=trans_format('log10', math_format(10^.x)))+labs(x="Forecasting Horizon",y="Size of Confidence Interval",color="Model Type") + theme_bw() + theme(text = element_text(size=22))
timeSeriesSpread %>% mutate(ForecastHorizon = Time-TrainingSize) %>% filter(ForecastHorizon>0,TrainingSize<100) %>%  group_by(ArchitectureType,ForecastHorizon) %>% summarise(MeanSpread=10^mean(log10(Spread)),SESpread=10^sd(log10(Spread))/sqrt(n()),maxSpread = max(Spread),minSpread = min(Spread)) %>%  ggplot(aes(ForecastHorizon,MeanSpread,color=ArchitectureType)) + geom_line(position=position_dodge(width=0.9),size=1,linetype=5)+scale_y_continuous(trans='log10',
                     breaks=trans_breaks('log10', function(x) 10^x),
                     labels=trans_format('log10', math_format(10^.x)))+labs(x="Forecasting Horizon",y="Size of Confidence Interval",color="Architecture Type") + theme_bw() + theme(text = element_text(size=22))+geom_ribbon(aes(ForecastHorizon,ymin = minSpread, ymax = maxSpread,fill=ArchitectureType),alpha = 0.1)+scale_fill_discrete(guide='none')

timeSeriesSpread %>% mutate(ForecastHorizon = Time-TrainingSize) %>% filter(ForecastHorizon>0,TrainingSize<100) %>%  group_by(ModelType,ForecastHorizon) %>% summarise(MeanSpread=10^mean(log10(Spread)),SESpread=10^sd(log10(Spread))/sqrt(n()),maxSpread = max(Spread),minSpread = min(Spread)) %>%  ggplot(aes(ForecastHorizon,MeanSpread,color=ModelType)) + geom_line(position=position_dodge(width=0.9),size=1,linetype=5)+scale_y_continuous(trans='log10',
                     breaks=trans_breaks('log10', function(x) 10^x),
                     labels=trans_format('log10', math_format(10^.x)))+labs(x="Forecasting Horizon",y="Size of Confidence Interval",color="Model Type") + theme_bw() + theme(text = element_text(size=22))+geom_ribbon(aes(ForecastHorizon,ymin = minSpread, ymax = maxSpread,fill=ModelType),alpha = 0.1)+scale_fill_discrete(guide='none')
```

